Added implementation for externalised weigher
tellor-io/substrate-parachain-node pull request #29
Opened 2023-06-13 10:21 UTC by pawanbisht62

This PR pertains to adding implementation for Weigher config item.

Updates:
Used Moonbeam's weights for weighing xcm message for remote execution.
 Resolves [issue](https://github.com/tellor-io/tellor-pallet/issues/120)

2023-06-14 06:53 UTC, evilrobot-01 requested changes
Looks great, thanks! Mostly minor docs related suggestions please.

2023-06-14 06:53 UTC, evilrobot-01 commented on Cargo.lock
> +source = "git+https://github.com/tellor-io/tellor-pallet?branch=pawan/externalise-xcm-message-weights#0938100c807a189ad7dc0c9da2d249299b0f4ff7"
Needs reverting to pallet main branch please.

2023-06-14 06:53 UTC, evilrobot-01 commented on runtime/src/lib.rs
> +use xcm_config::{XcmConfig, XcmOriginToTransactDispatchOrigin, MOONBASE};
Can we move the MOONBASE import into the function(s) using to keep it contained please? Unconventional, but I tried to keep the changes from the parachain template clean so it can easily be updated with newer versions.

2023-06-14 06:53 UTC, evilrobot-01 commented on runtime/src/lib.rs
> +use weights::moonbeam_xcm_benchmarks_generic::WeightInfo;
Can we move these imports into the function(s) using to keep it contained please? Unconventional, but I tried to keep the changes from the parachain template clean so it can easily be updated with newer versions.

2023-06-14 06:53 UTC, evilrobot-01 commented on runtime/src/lib.rs
> +pub struct XCMWeigher;
Can we rename to `Weigher` please, as it is also helping with the weight for the transact dispatchable call.

2023-06-14 06:53 UTC, evilrobot-01 commented on runtime/src/lib.rs
> +pub struct XCMWeigher;
I also used the convention of using `// TELLOR: comment` to any code block that is different to the parachain template so it is easy for anyone to identify what has changed.

Could you add a `// TELLOR: comment` above this code block please, with a comment on what it is doing and why?

2023-06-14 06:53 UTC, evilrobot-01 commented on runtime/src/lib.rs
> +		return match dest.into() {
Can remove the word `return` and the trailing semi-colon.

2023-06-14 06:53 UTC, evilrobot-01 commented on runtime/src/lib.rs
> +				for instruction in message.0.iter() {
Perhaps a comment here to say that we are reading weights from moonbeam-specific weight functions?

2023-06-14 06:53 UTC, evilrobot-01 commented on runtime/src/lib.rs
> +
Remove spacer line please, only so that the whole code block is annotated with `// TELLOR: comment`

2023-06-14 06:53 UTC, evilrobot-01 commented on runtime/src/lib.rs
> +		return match dest.into() {
Remove `return`

2023-06-14 06:53 UTC, evilrobot-01 commented on runtime/src/lib.rs
> +				// https://github.com/PureStake/moonbeam/blob/master/runtime/moonbase/src/lib.rs#L371-L375
Perhaps a comment here to say that we are calculating weight from gas limit as per moonbeam calculation?

2023-06-14 06:53 UTC, evilrobot-01 commented on runtime/src/weights/mod.rs
> +// Note: Modified file and used default weights for xcm instructions as current moonbeam implementation is dependent on pallet_erc20_xcm_bridge
Perhaps add ", which is not currently applicable" to the comment?

2023-06-14 06:53 UTC, evilrobot-01 commented on runtime/src/weights/mod.rs
> +// Moonbeam: https://github.com/PureStake/moonbeam/blob/master/pallets/moonbeam-xcm-benchmarks/src/weights/moonbeam_xcm_benchmarks_fungible.rs
Can you add a "// TELLOR: comment" above these modules please describing why they are imported (i.e. to provide actual weights from Moonbeam, used in calculating accurate weights for execution on destination parachain?

2023-06-15 22:27 UTC, oraclown approved these changes
Thanks, @pawanbisht62 !

2023-06-16 07:24 UTC, merged